---
resources:
- name: resource-tutorial
  type: git
  source:
    uri: https://github.com/qxing3/concourse-tutorial.git
    branch: develop
- name: resource-gist
  type: git
  source:
    branch: master
    uri: ((publishing-outputs-gist-uri))
    private_key: ((publishing-outputs-private-key))
- name: concourse-docker-image
  type: docker-image
  source:
    repository: ((docker-registry-concourse))
    tag: latest
    insecure_registries:
    - ((docker-registry))

jobs:
- name: job-bump-date
  serial: true
  plan:
  - get: resource-tutorial
  - get: resource-gist
  - task: bump-timestamp-file
    image: concourse-docker-image
    file: resource-tutorial/tutorials/basic/publishing-outputs/task-bump-timestamp.yml
  - put: resource-gist
    params:
      repository: updated-gist
